-- Ingredients table seeds here
INSERT INTO ingredients (name) VALUES ('avocado');
INSERT INTO ingredients (name) VALUES ('salt');
INSERT INTO ingredients (name) VALUES ('lime juice');
INSERT INTO ingredients (name) VALUES ('red onion');
INSERT INTO ingredients (name) VALUES ('serrano chiles');
INSERT INTO ingredients (name) VALUES ('cilantro');
INSERT INTO ingredients (name) VALUES ('black pepper');
INSERT INTO ingredients (name) VALUES ('tomato');
INSERT INTO ingredients (name) VALUES ('frozen cheese ravioli');
INSERT INTO ingredients (name) VALUES ('half-and-half cream');
INSERT INTO ingredients (name) VALUES ('smoked Gouda cheese');
INSERT INTO ingredients (name) VALUES ('parsley');
INSERT INTO ingredients (name) VALUES ('white pepper');
INSERT INTO ingredients (name) VALUES ('flour');
INSERT INTO ingredients (name) VALUES ('greek yogurt');
INSERT INTO ingredients (name) VALUES ('peanut oil');
INSERT INTO ingredients (name) VALUES ('eggs');
INSERT INTO ingredients (name) VALUES ('rice');
INSERT INTO ingredients (name) VALUES ('green onion');
INSERT INTO ingredients (name) VALUES ('frozen banana');
INSERT INTO ingredients (name) VALUES ('peanut butter');
INSERT INTO ingredients (name) VALUES ('cocoa powder');
INSERT INTO ingredients (name) VALUES ('unsweetened almond milk');
INSERT INTO ingredients (name) VALUES ('frozen pineapple chunks');
INSERT INTO ingredients (name) VALUES ('coconut milk');
INSERT INTO ingredients (name) VALUES ('canned corn');
INSERT INTO ingredients (name) VALUES ('mayonnaise');
INSERT INTO ingredients (name) VALUES ('sugar');
INSERT INTO ingredients (name) VALUES ('onion');
INSERT INTO ingredients (name) VALUES ('red chili');
INSERT INTO ingredients (name) VALUES ('unsalted butter');
INSERT INTO ingredients (name) VALUES ('mozzarella cheese');
INSERT INTO ingredients (name) VALUES ('white chocolate');
INSERT INTO ingredients (name) VALUES ('cream cheese');
INSERT INTO ingredients (name) VALUES ('olive oil');
INSERT INTO ingredients (name) VALUES ('pico de gallo');
INSERT INTO ingredients (name) VALUES ('feta cheese');
INSERT INTO ingredients (name) VALUES ('heavy cream');
INSERT INTO ingredients (name) VALUES ('chicken thighs');
INSERT INTO ingredients (name) VALUES ('soy sauce');
INSERT INTO ingredients (name) VALUES ('brown sugar');
INSERT INTO ingredients (name) VALUES ('milk');
INSERT INTO ingredients (name) VALUES ('elbow macaroni');
INSERT INTO ingredients (name) VALUES ('cheddar cheese');
INSERT INTO ingredients (name) VALUES ('spinach');
INSERT INTO ingredients (name) VALUES ('sundried tomato');
INSERT INTO ingredients (name) VALUES ('filo pastry');
INSERT INTO ingredients (name) VALUES ('strawberries');
INSERT INTO ingredients (name) VALUES ('honey');
INSERT INTO ingredients (name) VALUES ('garlic');
INSERT INTO ingredients (name) VALUES ('parmesan cheese');
INSERT INTO ingredients (name) VALUES ('sunflower oil');
INSERT INTO ingredients (name) VALUES ('water');
INSERT INTO ingredients (name) VALUES ('dry yeast');
INSERT INTO ingredients (name) VALUES ('sesame seeds');
INSERT INTO ingredients (name) VALUES ('turkey smoked sausage');
INSERT INTO ingredients (name) VALUES ('cajun seasoning');
INSERT INTO ingredients (name) VALUES ('chicken breast');
INSERT INTO ingredients (name) VALUES ('pesto');
INSERT INTO ingredients (name) VALUES ('heavy whipping cream');
INSERT INTO ingredients (name) VALUES ('gelatin');
INSERT INTO ingredients (name) VALUES ('vanilla extract');
INSERT INTO ingredients (name) VALUES ('tortilla');
INSERT INTO ingredients (name) VALUES ('black beans');
INSERT INTO ingredients (name) VALUES ('hot chilli sauce');
INSERT INTO ingredients (name) VALUES ('sour cream');
INSERT INTO ingredients (name) VALUES ('dried dill weed');
INSERT INTO ingredients (name) VALUES ('garlic powder');
INSERT INTO ingredients (name) VALUES ('masa harina');
INSERT INTO ingredients (name) VALUES ('frozen vegetables');
INSERT INTO ingredients (name) VALUES ('raisins');
INSERT INTO ingredients (name) VALUES ('vegetable stock cube');
INSERT INTO ingredients (name) VALUES ('korma curry paste');
INSERT INTO ingredients (name) VALUES ('cashew nuts');
INSERT INTO ingredients (name) VALUES ('cannoli shells');
INSERT INTO ingredients (name) VALUES ('ricotta cheese');
INSERT INTO ingredients (name) VALUES ('confectioners sugar');
INSERT INTO ingredients (name) VALUES ('mini chocolate chips');
INSERT INTO ingredients (name) VALUES ('orange zest');
INSERT INTO ingredients (name) VALUES ('watercress');
INSERT INTO ingredients (name) VALUES ('chives');
INSERT INTO ingredients (name) VALUES ('lemon zest');
INSERT INTO ingredients (name) VALUES ('garlic soft cheese');
INSERT INTO ingredients (name) VALUES ('coconut yogurt');
INSERT INTO ingredients (name) VALUES ('cucumber');
INSERT INTO ingredients (name) VALUES ('fresh dill');
INSERT INTO ingredients (name) VALUES ('lemon juice');
INSERT INTO ingredients (name) VALUES ('chickpeas');
INSERT INTO ingredients (name) VALUES ('baguette');

