-- Measurements table seeds here
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('2', 1, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 2, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 3, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 4, 1);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 5, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 6, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 7, 1);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1/2', 8, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('16', 'oz', 9, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 10, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 11, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 12, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 13, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1 1/4', 'cup', 14, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 15, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 16, 4);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('4', 17, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 18, 4);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'tsp', 2, 4);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('4', 19, 4);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 20, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 21, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'cup', 22, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 23, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 24, 6);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 25, 6);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('15', 'oz', 26, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'tbsp', 27, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 28, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 2, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 7, 7);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1/4', 29, 7);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 30, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 31, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 32, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('9', 'oz', 33, 8);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('8', 'oz', 34, 8);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('6', 17, 8);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/3', 'cup', 35, 9);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('6', 'cup', 36, 9);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 2, 9);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3 1/2', 'oz', 37, 9);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('6', 17, 9);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 7, 9);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('4', 'lb', 8, 10);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tsp', 2, 10);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'tsp', 7, 10);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('6', 'tbsp', 35, 10);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 29, 10);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 38, 10);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'lb', 39, 11);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 40, 11);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 41, 11);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('5', 'cup', 42, 12);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'lb', 43, 12);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'cup', 44, 12);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('200', 'g', 45, 13);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('175', 'g', 46, 13);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('100', 'g', 37, 13);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('2', 17, 13);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('125', 'g', 47, 13);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('125', 'g', 25, 14);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('125', 'g', 48, 14);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('125', 'g', 20, 14);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('125', 'g', 49, 14);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1/2', 20, 15);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 48, 15);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 25, 15);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('8', 'oz', 43, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'tbsp', 31, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'clove', 50, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('6', 'cup', 45, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 51, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 7, 16);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('5', 'cup', 14, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tsp', 28, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1.5', 'tsp', 2, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 52, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1 1/2', 'cup', 53, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 7, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'package', 54, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tsp', 55, 17);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('14', 'oz', 56, 18);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('8', 'oz', 43, 18);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'cup', 38, 18);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 57, 18);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 51, 18);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'lb', 58, 19);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'cup', 59, 19);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 8, 19);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'cup', 32, 19);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3/4', 'cup', 42, 20);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3/4', 'cup', 60, 20);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'oz', 61, 20);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/3', 'cup', 28, 20);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'tsp', 62, 20);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 52, 21);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 63, 21);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 17, 21);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('200', 'g', 64, 21);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'tbsp', 3, 21);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1/2', 1, 21);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('50', 'g', 37, 21);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'tbsp', 65, 21);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('8', 'oz', 34, 22);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'cup', 66, 22);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('4', 'oz', 37, 22);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tsp', 68, 22);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tsp', 67, 22);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 69, 23);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 2, 23);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'cup', 53, 23);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 35, 23);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('250', 'g', 18, 24);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('400', 'g', 70, 24);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 71, 24);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 72, 24);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 73, 24);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 74, 24);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('8', 75, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'cup', 76, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 77, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3/4', 'cup', 78, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1 1/2', 'tsp', 62, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tsp', 79, 25);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('50', 'g', 80, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 81, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 82, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('5', 'tbsp', 83, 26);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('2', 58, 26);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('2', 63, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('30', 'g', 44, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('30', 'g', 32, 26);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 84, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'cup', 85, 27);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 50, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 86, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 35, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 87, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 2, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 7, 27);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 88, 28);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 89, 28);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tbsp', 12, 28);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('6', 46, 28);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 35, 28);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tbsp', 87, 28);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('2', 50, 28);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 2, 28);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'tsp', 7, 28);
