-- Measurements table seeds here
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'ripe', 1, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'teaspoon', 2, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'tablespoon', 3, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tablespoon', 4, 1);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('1', 5, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tablespoon', 6, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'teaspoon', 7, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'ripe', 8, 1);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('16', 'ounce', 9, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 10, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 11, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'teaspoon', 12, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'teaspoon', 13, 2);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1 1/4', 'cup', 14, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'cup', 15, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tablespoon', 16, 4);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('4', 17, 3);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 18, 4);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/2', 'teaspoon', 2, 4);
INSERT INTO measurements (amount, ingredient_id, recipe_id) VALUES ('4', 19, 4);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cups', 20, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tablespoon', 21, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1/4', 'cup', 22, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('2', 'tablespoon', 23, 5);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('3', 'cup', 24, 6);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 25, 6);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 26, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 27, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 28, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 2, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 7, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 29, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 30, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 31, 7);
INSERT INTO measurements (amount, unit, ingredient_id, recipe_id) VALUES ('1', 'can', 32, 7);
