-- Cultures table seeds here
INSERT INTO cultures (recipe_id, name) VALUES (1, 'Mexican');
INSERT INTO cultures (recipe_id, name) VALUES (2, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (3, 'Indian');
INSERT INTO cultures (recipe_id, name) VALUES (4, 'Chinese');
INSERT INTO cultures (recipe_id, name) VALUES (5, 'American');
INSERT INTO cultures (recipe_id, name) VALUES (6, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (7, 'Korean');
INSERT INTO cultures (recipe_id, name) VALUES (8, 'Japanese');
INSERT INTO cultures (recipe_id, name) VALUES (9, 'Mediterranean');
INSERT INTO cultures (recipe_id, name) VALUES (10, 'Spanish');
INSERT INTO cultures (recipe_id, name) VALUES (11, 'Japanese');
INSERT INTO cultures (recipe_id, name) VALUES (12, 'American');
INSERT INTO cultures (recipe_id, name) VALUES (13, 'Greek');
INSERT INTO cultures (recipe_id, name) VALUES (14, 'American');
INSERT INTO cultures (recipe_id, name) VALUES (15, 'American');
INSERT INTO cultures (recipe_id, name) VALUES (16, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (17, 'Turkish');
INSERT INTO cultures (recipe_id, name) VALUES (18, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (19, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (20, 'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (21, 'Mexican');
INSERT INTO cultures (recipe_id, name) VALUES (22,'Mediterranean');
INSERT INTO cultures (recipe_id, name) VALUES (23,'Mexican');
INSERT INTO cultures (recipe_id, name) VALUES (24,'Indian');
INSERT INTO cultures (recipe_id, name) VALUES (25,'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (26,'Mexican');
INSERT INTO cultures (recipe_id, name) VALUES (26,'Spanish');
INSERT INTO cultures (recipe_id, name) VALUES (27,'Mediterranean');
INSERT INTO cultures (recipe_id, name) VALUES (27,'Greek');
INSERT INTO cultures (recipe_id, name) VALUES (28,'Italian');
INSERT INTO cultures (recipe_id, name) VALUES (28,'Mediterranean');
INSERT INTO cultures (recipe_id, name) VALUES (29,'Mexican');
INSERT INTO cultures (recipe_id, name) VALUES (30,'American');
INSERT INTO cultures (recipe_id, name) VALUES (31,'American');
INSERT INTO cultures (recipe_id, name) VALUES (31,'Italian');
